---
- hosts: localhost
  tasks:
  - name: Sync latest ansible-pull-batch.sh into environment
    get_url:
      url: https://github.com/LostLakkris/ansible-pull-batch/raw/master/ansible-pull-batch.sh
      dest: /usr/bin
      mode: "0755"
